-- MySQL Script generated by MySQL Workbench
-- Wed May 13 15:44:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EncoreLand
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EncoreLand
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EncoreLand` DEFAULT CHARACTER SET utf8 ;
USE `EncoreLand` ;

-- -----------------------------------------------------
-- Table `EncoreLand`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EncoreLand`.`customer` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `sex` VARCHAR(45) NULL,
  `age` INT NULL,
  `type` INT NULL,
  PRIMARY KEY (`no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EncoreLand`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EncoreLand`.`employee` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `dept` VARCHAR(45) NULL,
  PRIMARY KEY (`no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EncoreLand`.`attraction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EncoreLand`.`attraction` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `repairdate` VARCHAR(45) NULL,
  `price` INT NULL,
  `cost` INT NULL,
  PRIMARY KEY (`no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EncoreLand`.`uselist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EncoreLand`.`uselist` (
  `customer_no` INT NOT NULL,
  `attraction_no` INT NOT NULL,
  `usedate` VARCHAR(45) NULL,
  INDEX `fk_customer_has_attraction_attraction1_idx` (`attraction_no` ASC) VISIBLE,
  INDEX `fk_customer_has_attraction_customer_idx` (`customer_no` ASC) VISIBLE,
  CONSTRAINT `fk_customer_has_attraction_customer`
    FOREIGN KEY (`customer_no`)
    REFERENCES `EncoreLand`.`customer` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_has_attraction_attraction1`
    FOREIGN KEY (`attraction_no`)
    REFERENCES `EncoreLand`.`attraction` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EncoreLand`.`fix`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EncoreLand`.`fix` (
  `attraction_no` INT NOT NULL,
  `employee_no` INT NOT NULL,
  INDEX `fk_repair_attraction1_idx` (`attraction_no` ASC) VISIBLE,
  CONSTRAINT `fk_repair_attraction1`
    FOREIGN KEY (`attraction_no`)
    REFERENCES `EncoreLand`.`attraction` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repair_manager1`
    FOREIGN KEY (`employee_no`)
    REFERENCES `EncoreLand`.`employee` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- 1000번부터 autoincrement, attraction 입력
alter table attraction auto_increment = 1000;
INSERT INTO attraction VALUES(null,"회전목마","2020-1-1",5000,2000000);
INSERT INTO attraction VALUES(null,"바이킹","2020-3-4",6000,1000000);
INSERT INTO attraction VALUES(null,"롤러코스터","2020-2-5",7000,3000000);
INSERT INTO attraction VALUES(null,"유령의집","2020-4-7",8000,1000000);
INSERT INTO attraction VALUES(null,"독수리요새","2019-12-13",4000,1500000);
INSERT INTO attraction VALUES(null,"청룡열차","2019-10-21",5000,1600000);
INSERT INTO attraction VALUES(null,"허리캐인","2020-7-1",5000,1000000);
INSERT INTO attraction VALUES(null,"하늘자전거","2020-9-1",6000,1400000);
INSERT INTO attraction VALUES(null,"다람쥐통","2020-10-1",7000,1000000);
INSERT INTO attraction VALUES(null,"범버카","2020-11-1",9000,4550000);
-- 100번부터 autoincrement, manager 입력
alter table employee auto_increment = 100;
INSERT INTO employee VALUES(null,'강호동','Repairman');
INSERT INTO employee VALUES(null,'유재석','Repairman');
INSERT INTO employee VALUES(null,'이수근','Repairman');
INSERT INTO employee VALUES(null,'조세호','Cleaner');
INSERT INTO employee VALUES(null,'박명수','Repairman');
INSERT INTO employee VALUES(null,'전지현','Cleaner');
INSERT INTO employee VALUES(null,'박나래','Repairman');
INSERT INTO employee VALUES(null,'김태희','Clerk');
INSERT INTO employee VALUES(null,'김희애','Repairman');
INSERT INTO employee VALUES(null,'임수정','Clerk');
INSERT INTO employee VALUES(null,'윤두준','Repairman');
INSERT INTO employee VALUES(null,'송중기','Cleaner');
INSERT INTO employee VALUES(null,'송혜교','Clerk');
INSERT INTO employee VALUES(null,'조보아','Repairman');

-- fix 에  alter delete cascade 추가하세요
INSERT INTO fix VALUES('1000',100);
INSERT INTO fix VALUES('1001',101);
INSERT INTO fix VALUES('1002',102);
INSERT INTO fix VALUES('1003',104);
INSERT INTO fix VALUES('1004',106);
INSERT INTO fix VALUES('1005',108);
INSERT INTO fix VALUES('1006',110);
INSERT INTO fix VALUES('1007',113);
INSERT INTO fix VALUES('1008',104);
INSERT INTO fix VALUES('1009',106);
