-- MySQL Script generated by MySQL Workbench
-- Thu May 14 11:11:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema encoreland
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema encoreland
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `encoreland` DEFAULT CHARACTER SET utf8 ;
USE `encoreland` ;

-- -----------------------------------------------------
-- Table `encoreland`.`attraction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encoreland`.`attraction` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `limitage` INT NULL DEFAULT NULL,
  `maxperson` INT NULL DEFAULT NULL,
  `info` VARCHAR(45) NULL,
  PRIMARY KEY (`no`))
ENGINE = InnoDB
AUTO_INCREMENT = 1020
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `encoreland`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encoreland`.`customer` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `sex` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  PRIMARY KEY (`no`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `encoreland`.`uselist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encoreland`.`uselist` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `customer_no` INT NOT NULL,
  `attraction_no` INT NOT NULL,
  `usedate` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT NULL,
  INDEX `fk_customer_has_attraction_attraction1_idx` (`attraction_no` ASC) VISIBLE,
  INDEX `fk_customer_has_attraction_customer_idx` (`customer_no` ASC) VISIBLE,
  PRIMARY KEY (`no`),
  CONSTRAINT `fk_customer_has_attraction_attraction1`
    FOREIGN KEY (`attraction_no`)
    REFERENCES `encoreland`.`attraction` (`no`),
  CONSTRAINT `fk_customer_has_attraction_customer`
    FOREIGN KEY (`customer_no`)
    REFERENCES `encoreland`.`customer` (`no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- 1000번부터 autoincrement, attraction 입력
alter table attraction auto_increment = 1000;
INSERT INTO attraction VALUES(null,"회전목마",9,20,'남녀노소 즐거운 회전목마');
INSERT INTO attraction VALUES(null,"바이킹",15,20,'우리나라 최고 아찔한 바이킹');
INSERT INTO attraction VALUES(null,"롤러코스터",19,10,'세계에서 제일 급격한 경사의 롤코');
INSERT INTO attraction VALUES(null,"유령의집",16,4,'심신미약과 노약자 임산부는 제한');
INSERT INTO attraction VALUES(null,"독수리요새",15,8,'모두 독수리가 되어보아요~_~');
INSERT INTO attraction VALUES(null,"청룡열차",6,14,'아이들 인기만점 * 귀여운 스릴 *');
INSERT INTO attraction VALUES(null,"허리캐인",19,16,'허리케인 속으로 빠져보기 ><');
INSERT INTO attraction VALUES(null,"하늘자전거",11,9,'우리모두 하늘을 날아보아요 ~_~');
INSERT INTO attraction VALUES(null,"다람쥐통",6,10,'다람쥐가 되어 다람쥐랑 친구해보아요 ><');
INSERT INTO attraction VALUES(null,"범버카",9,9,'다치기 싫으면 알아서 비키자 ㅎ 안전운전 ! ');

ALTER TABLE customer
RENAME COLUMN no TO customer_no;
ALTER TABLE attraction
RENAME COLUMN no TO attraction_no;
ALTER TABLE uselist
RENAME COLUMN no TO uselist_no;
